spring:
    application:
        name: gtc-trading-gateway
    jackson:
        property-naming-strategy: SNAKE_CASE
        locale: en_US
        serialization:
            fail-on-empty-beans: false
            write_dates_as_timestamps: false
server:
    servlet-path: /api
    port: 9999
app:
    gdax:
        restBase:
        wsBase:
        passphrase: ${GDAX_PASSPHRASE}
        publicKey: ${GDAX_PUBLIC}
        secretKey: ${GDAX_SECRET}
        pairs:
            BTCUSD=BTC-USD,
            LTCBTC=LTC-BTC,
            XMRBTC=XMR-BTC
    binance:
        restBase: "https://api.binance.com"
        wsBase:
        passphrase: ${BINANCE_PASSPHRASE}
        publicKey: ${BINANCE_PUBLIC}
        secretKey: ${BINANCE_SECRET}
        pairs:
            BTCUSD=BTC-USD,
            LTCBTC=LTC-BTC,
            XMRBTC=XMR-BTC
    bitfinex:
#        restBase: "https://api.bitfinex.com"
        restBase: "http://localhost:8081"
        wsBase: ""
        passphrase: ${BITFINEX_PASSPHRASE}
        publicKey: ${BITFINEX_PUBLIC}
        secretKey: ${BITFINEX_SECRET}
        pairs:
            BTCUSD=BTC-USD,
            LTCBTC=LTC-BTC,
            XMRBTC=XMR-BTC
        disconnectIfInactiveS: 20
    hitbtc:
        restBase: "https://api.hitbtc.com/api/2"
        wsBase: "wss://api.hitbtc.com/api/2/ws"
        passphrase: ${HITBTC_PASSPHRASE}
        publicKey: ${HITBTC_PUBLIC}
        secretKey: ${HITBTC_SECRET}
        pairs:
            BTCUSD=BTC-USD,
            LTCBTC=LTC-BTC,
            XMRBTC=XMR-BTC
        disconnectIfInactiveS: 20
debug: true
logging:
    level: DEBUG

