spring:
    application:
        name: gtc-trading-gateway
    jackson:
        property-naming-strategy: SNAKE_CASE
        locale: en_US
        serialization:
            fail-on-empty-beans: false
            write_dates_as_timestamps: false
    artemis:
        host: ${ESB_AMQ_ADDRESS}
        port: 61616
        mode: native
        user: artemis
        password: artemis
    jms:
        template:
            qos-enabled: true
            delivery-mode: persistent
server:
    servlet-path: /api
    port: 8084
app:
    gdax:
        restBase:
        wsBase:
        passphrase: ${GDAX_PASSPHRASE}
        publicKey: ${GDAX_PUBLIC}
        secretKey: ${GDAX_SECRET}
        pairs:
            BTC-USD=BTC-USD,
            LTC-BTC=LTC-BTC,
            XMR-BTC=XMR-BTC
        ratePerM: 60
    binance:
        restBase: "https://api.binance.com"
        passphrase: ${BINANCE_PASSPHRASE}
        publicKey: ${BINANCE_PUBLIC}
        secretKey: ${BINANCE_SECRET}
        pairs:
            # USD is actually tether
            LTC-BTC=LTCBTC,
            XMR-BTC=XMRBTC,
            ETH-BTC=ETHBTC,
            DASH-BTC=DASHBTC,
            BTC-USDT=BTCUSDT,
            LTC-USDT=LTCUSDT,
            ETH-USDT=ETHUSDT
        ratePerM: 60
    bitfinex:
        restBase: "https://api.bitfinex.com"
        wsBase: "wss://api.bitfinex.com/ws/2"
        passphrase: ${BITFINEX_PASSPHRASE}
        publicKey: ${BITFINEX_PUBLIC}
        secretKey: ${BITFINEX_SECRET}
        pairs:
            BTC-USD=BTCUSD,
            LTC-BTC=LTCBTC,
            XMR-BTC=XMRBTC,
            DASH-BTC=DASHBTC
        customCurrencyName:
            BTC=bitcoin,
            LTC=litecoin,
            XMR=monero
        ratePerM: 60
    hitbtc:
        restBase: "https://api.hitbtc.com/api/2"
        wsBase: "wss://api.hitbtc.com/api/2/ws"
        publicKey: ${HITBTC_PUBLIC}
        secretKey: ${HITBTC_SECRET}
        pairs:
            # USD is actually usdt
            BTC-USD=BTCUSD,
            LTC-BTC=LTCBTC,
            XMR-BTC=XMRBTC,
            ETH-BTC=ETHBTC,
            DASH-BTC=DASHBTC,
            BTC-USDT=BTCUSD,
            LTC-USDT=LTCUSD,
            XMR-USDT=XMRUSD,
            ETH-USDT=ETHUSD,
            XRP-USDT=XRPUSD,
            DASH-USDT=DASHUSD
        customResponseCurrencyMapping:
            USD=USDT
        ratePerM: 60
    wex:
        restBase: "https://wex.nz/tapi"
        publicKey: ${WEX_PUBLIC}
        secretKey: ${WEX_SECRET}
        pairs:
            BTC-USD=btc_usd,
            LTC-BTC=ltc_btc,
            DASH-BTC=dsh_btc,
            DASH-LTC=dsh_ltc
        customResponseCurrencyMapping:
            dsh=DASH
        ratePerM: 60
    mock:
        restBase: "http://localhost:9090/api"
        publicKey: trade-gateway
        pairs:
            BTC-USDT=BTCUSDT
        customResponseCurrencyMapping:
            Bitcoin=BTC,
            Tether=USDT
        ratePerM: 60
    clients:
        # all-clients: bitfinex,binance,wex,hitbtc
        # mocks (need MOCK_ENABLED as true): mock-asia,mock-europe
        active: bitfinex,binance,wex,hitbtc
    schedule:
        puppeteerS: 10
    jms:
        receiveTimeout: 50
        queue:
            in:
                account: do-account
                create: do-create
                manage: do-manage
                withdraw: do-withdraw
            out:
                account: done-account
                create: done-create
                manage: done-manage
                withdraw: done-withdraw
    async:
        pool:
            core: 10
            max: 50
    statistics:
        enabled: true
        reportIntervalMs: 60000
        window: 1000

