spring:
    application:
        name: gtc-trading-gateway
    jackson:
        property-naming-strategy: SNAKE_CASE
        locale: en_US
        serialization:
            fail-on-empty-beans: false
            write_dates_as_timestamps: false
server:
    servlet-path: /api
    port: 9999
app:
    gdax:
        restBase:
        passphrase: ${GDAX_PASSPHRASE}
        publicKey: ${GDAX_PUBLIC}
        secretKey: ${GDAX_SECRET}
    binance:
        restBase: "https://api.binance.com"
        passphrase: ${BINANCE_PASSPHRASE}
        publicKey: ${BINANCE_PUBLIC}
        secretKey: ${BINANCE_SECRET}
        pairs:
            BTCUSD=BTC-USD,
            LTCBTC=LTC-BTC,
            XMRBTC=XMR-BTC
    hitbtc:
        restBase: "https://api.hitbtc.com/api/2"
        wsBase: "wss://api.hitbtc.com/api/2/ws"
        passphrase: ${HITBTC_PASSPHRASE}
        publicKey: ${HITBTC_PUBLIC}
        secretKey: ${HITBTC_SECRET}
        pairs:
            BTCUSD=BTC-USD,
            LTCBTC=LTC-BTC,
            XMRBTC=XMR-BTC
debug: true
logging:
    level: DEBUG

