spring:
    application:
        name: gtc-trading-gateway
    jackson:
        property-naming-strategy: SNAKE_CASE
        locale: en_US
        serialization:
            fail-on-empty-beans: false
            write_dates_as_timestamps: false
    activemq:
        broker-url: ${ESB_AMQ_ADDRESS}
        non-blocking-redelivery: true
        pool:
            block-if-full: true
            block-if-full-timeout: -1
            create-connection-on-startup: true
            enabled: false
            expiry-timeout: 10000
            idle-timeout: 30000
            max-connections: 1
            maximum-active-session-per-connection: 500
            reconnect-on-exception: true
            time-between-expiration-check: -1
            use-anonymous-producers: true
        packages:
            trusted: com.gtc.model,java.time,java.math
    jms:
        pub-sub-domain: true
server:
    servlet-path: /api
    port: 8084
app:
    gdax:
        restBase:
        wsBase:
        passphrase: ${GDAX_PASSPHRASE}
        publicKey: ${GDAX_PUBLIC}
        secretKey: ${GDAX_SECRET}
        pairs:
            BTC-USD=BTC-USD,
            LTC-BTC=LTC-BTC,
            XMR-BTC=XMR-BTC
        ratePerS: 0.17
    binance:
        restBase: "https://api.binance.com"
        passphrase: ${BINANCE_PASSPHRASE}
        publicKey: ${BINANCE_PUBLIC}
        secretKey: ${BINANCE_SECRET}
        pairs:
            BTC-USD=BTC-USD,
            LTC-BTC=LTC-BTC,
            XMR-BTC=XMR-BTC
        ratePerS: 0.17
    hitbtc:
        restBase: "https://api.hitbtc.com/api/2"
        wsBase: "wss://api.hitbtc.com/api/2/ws"
        publicKey: ${HITBTC_PUBLIC}
        secretKey: ${HITBTC_SECRET}
        pairs:
            BTC-USD=BTCUSD,
            LTC-BTC=LTCBTC,
            XMR-BTC=XMRBTC
        ratePerS: 0.17
    wex:
        restBase: "https://wex.nz/tapi"
        publicKey: ${WEX_PUBLIC}
        secretKey: ${WEX_SECRET}
        pairs:
            BTC-USD=btc_usd,
            LTC-BTC=ltc_btc,
            DASH-BTC=dsh_btc,
            DASH-LTC=dsh_ltc
        customResponseCurrencyMapping:
            dsh=DASH
        ratePerS: 0.17
    clients:
        active: wex,hitbtc
    schedule:
        puppeteerS: 10
    jms:
        topic:
            inOut:
                account: account
                create: create
                manage: manage
                withdraw: withdraw

