spring:
    application:
        name: gtc-trading-gateway
    jackson:
        property-naming-strategy: SNAKE_CASE
        locale: en_US
        serialization:
            fail-on-empty-beans: false
            write_dates_as_timestamps: false
    activemq:
        broker-url: ${ESB_AMQ_ADDRESS}
        non-blocking-redelivery: true
        pool:
            block-if-full: true
            block-if-full-timeout: -1
            create-connection-on-startup: true
            enabled: false
            expiry-timeout: 10000
            idle-timeout: 30000
            max-connections: 1
            maximum-active-session-per-connection: 500
            reconnect-on-exception: true
            time-between-expiration-check: -1
            use-anonymous-producers: true
        packages:
            trusted: com.gtc.model,java.time,java.math
    jms:
        pub-sub-domain: true
server:
    servlet-path: /api
    port: 8084
app:
    gdax:
        restBase:
        wsBase:
        passphrase: ${GDAX_PASSPHRASE}
        publicKey: ${GDAX_PUBLIC}
        secretKey: ${GDAX_SECRET}
        pairs:
            BTCUSD=BTC-USD,
            LTCBTC=LTC-BTC,
            XMRBTC=XMR-BTC
        ratePerS: 0.17
    binance:
        restBase: "https://api.binance.com"
        passphrase: ${BINANCE_PASSPHRASE}
        publicKey: ${BINANCE_PUBLIC}
        secretKey: ${BINANCE_SECRET}
        pairs:
            BTCUSD=BTC-USD,
            LTCBTC=LTC-BTC,
            XMRBTC=XMR-BTC
        ratePerS: 0.17
    hitbtc:
        restBase: "https://api.hitbtc.com/api/2"
        wsBase: "wss://api.hitbtc.com/api/2/ws"
        passphrase: ${HITBTC_PASSPHRASE}
        publicKey: ${HITBTC_PUBLIC}
        secretKey: ${HITBTC_SECRET}
        pairs:
            BTCUSD=BTC-USD,
            LTCBTC=LTC-BTC,
            XMRBTC=XMR-BTC
        disconnectIfInactiveS: 20
        ratePerS: 0.17
    jms:
        topic:
            inOut:
                create: create
                manage: manage
                withdraw: withdraw
debug: true
logging:
    level: DEBUG

